blank_issues_enabled: false
contact_links:
  - name: ❓ Question - GitHub Discussions
    url: https://github.com/9mbs/calendar-widgets/discussions
    about: Please use this link to ask questions about the library. This is the best place to get help with your project.
